### ISSUE TITLE
Salt representation

### ISSUE THREAD

**Issue by marcosfelt** [MoleculeResolver/molecule-resolver#6]
Salts can be represented either as their ionic form or semi-covalent bonds. For example:

Ionic: `[Fe+3].[Fe+3].[O-2].[O-2].[O-2]`
Covalent: `O=[Fe]O[Fe]=O` 

Should we have a standard that we convert to? Should we allow users to select which one they want?

**Comment by simonmb** [comment]
the commit 148058c9eb49863d5359c0f3fe28a3e9837f545e adds the capability to choose to disconnect more ions when salts are encountered.

**Comment by marcosfelt** [comment]
Great work  - thanks Simon!
