### ISSUE TITLE
Handling tautomers

### ISSUE THREAD

**Issue by marcosfelt** [MoleculeResolver/molecule-resolver#7]
from an email 

> Regarding cytosine. The movement of the H is probably a tautomeric transformation. MoleculeResolver considers tautomers to be different so far. This needs some discussion. I would say probably both are correct, but one is more prevalent in water. The thing is, if you go other solvents this could change

**Comment by simonmb** [comment]
MoleculeResolver can now be configured to consider tautomers as equivalent.
